### ISSUE TITLE
[BUG] not @computed decorators work in file.js but fail in file.ts

### ISSUE THREAD

**Issue by bartocc** [ember-decorators/ember-decorators#162]
# ember-decorators version

yarn list v0.27.5
└─ ember-decorators@1.2.2
Done in 1.11s.

# how to reproduce ?

- Clone https://github.com/bartocc/typescript-and-decorators
- run `ember serve`
- open `http://localhost:4200/` and the browser's console

=> you should get the followin JS error

```js
ember.debug.js:19840 TypeError: Cannot read property 'enumerable' of undefined
    at handleDescriptor (decorator-wrappers.js:15)
    at decorator-wrappers.js:43
    at __decorate (component.js:68)
    at Module.callback (component.js:100)
    at Module.exports (loader.js:106)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:387)
    at Class.resolveOther (index.js:108)
    at Class.superWrapper [as resolveOther] (ember.debug.js:42856)
    at Class.resolve (ember.debug.js:7200)
```

- stop your server
- rename app/components/foo-bar/component.ts to component.js
- start your server again

=> you should get no JS error and the following text rendered in the browser

```
I am foo bar 
B
```

**Comment by bartocc** [comment]
@pzuraq took a stab at it and reported his findings in the following slack discussion

https://embercommunity.slack.com/archives/C64BW2L9X/p1503506282000634

**Comment by pzuraq** [comment]
The slack archive has disappeared here so going to report my findings for posterity:

According to the decorators/class fields specs, class fields which are decorated will not actually have a descriptor on the class _before_ the decorator is run. This makes sense as class fields are not prototype state but instance state - they aren't assigned until the constructor of the instance runs.

Babel is actually in the wrong here, and all of our decorators assume that a descriptor will exist and we can use its properties because that's how it currently transpiles it. Typescript has it right, we'll have to make decorators for class fields which don't have descriptors.

**Comment by bartocc** [comment]
Should we also create a ticket on the babel repo ?

**Comment by pzuraq** [comment]
I believe they're currently rewriting a lot of things, but yeah may be a good idea to open it so they're aware

**Comment by pzuraq** [comment]
Verified that this appears to be fixed on Babel 7, we should update and close this once it's released.

**Comment by bartocc** [comment]
@pzuraq if I understand all this correctly, when using Babel 7 or TypeScript, you get the same error, right ?

So ember-decorators still needs to handle situations where there are no descriptors.

**Comment by theseyi** [comment]
That seems correct @bartocc, ran into this issue this morning with TypeScript. For class fields, TypeScript will pass the descriptor argument: `desc` as `undefined`. Ember computed decorators, for example `@alias` is created with `decoratedPropertyWithRequiredParams`, which further invokes `decoratorWithParams`. The returned closure checks if the last argument is a descriptor, and if not as it the case with class fields invokes `handleDescriptor` with the arguments object, the decorator function and any params.

The problem here is that `handleDescriptor` is the wrong function to call here since there is *no descriptor* but in the case of TypeScript, `undefined` the parameter is always undefined, which leads to the exception above.

**Comment by pzuraq** [comment]
Actually looking at more recent versions of the spec, it looks like both of them may need an update. It's hard to say exactly (spec language being notoriously difficult to read) but these are the two relevant sections:

1. [DecorateElement](https://tc39.github.io/proposal-unified-class-features/#sec-decorate-element)
2. [FromElementDescriptor](https://tc39.github.io/proposal-unified-class-features/#sec-decorate-element)

If I'm reading this correctly (and that's a big if) it looks like the decorator API is going to change to return quite a bit more information, and the signature of decorators will change to `fn(elementObject)` where `elementObject` contains all of that info.

In the end the spec is in flux so I don't think we can say for sure who is right here. For some of the decorators we have we can definitely account for there being no way to access the initializer, but for others we may need the value (and be dead in the water). Either way, we should fix the decorators for now and wait for the next revision of TS and Babel to try to sort it out.

**Comment by pzuraq** [comment]
Update on this:

The behavior differences between Typescript decorators and the Babel decorators that `ember-decorators` were designed for are larger than it seemed at first. Supporting TS now would likely mean having to rewrite a lot of the current logic, and some behavior simply may not work in TS since we don't have any way of accessing class field descriptors.

Babel is [currently implementing the Stage 2 decorators spec](https://github.com/babel/babel/pull/6107), so we'll have to update either way once that lands. The [TS design meeting notes](https://github.com/Microsoft/TypeScript/issues/19169) indicate that they won't be updating anything until decorators reach stage 3, per their policy (only implement stage 3 features), so it could be a while 😕

**Comment by bartocc** [comment]
thx for the update @pzuraq. I guess for the time being, using ember-decorators means not using ember-cli-typescript 😕

**Comment by pzuraq** [comment]
v2.0.0-beta.1 has been released and should fix these issues! Let me know if you have any problems, I'll close this issue once we get to v2.0.0 stable
