### ISSUE TITLE
Decorator @action on Components can override event hooks

### ISSUE THREAD

**Issue by Gorzas** [ember-decorators/ember-decorators#163]
Having the following component:

```
// components/parent-component.js
export default Component {
  value = ''

  @action
  change() {
    // do stuff...
  }
}
```
With the following template:

```
// templates/components/parent-component.hbs
{{children-component
  onChange=(action "change")
  value=(mut value)
}}
```

I've found that the action `change` on the parent it's executed twice every time the children component call the action `onChange` and change the `value`. I don't know if my code is correct or not, but this behaviour is different than using the old way with the `actions` object.

**Comment by pzuraq** [comment]
This was a design decision made when we implemented the `@action` decorator. Under the hood all it does is add a function to the class's `actions` object which calls the original decorated function:

```
export default class FooComponent extends Component {
  change() {
    // do stuff...
  }

  actions = {
    change() {
      this.change();
    }
  }
}
```

We made the decision to do this because removing a decorated function from the class would probably be confusing, since it looks like it should exist and be callable. This does mean that lifecycle hooks can be clobbered, unfortunately. However, because actions are only used internally it does not restrict the component's public API (`sendAction` cannot be clobbered), so it just means you'll have to use a different names to avoid conflicts.

Sidenote: It's strange to me that the `change` action is triggering on an arbitrary component, it shouldn't be a lifecycle hook in general, only for `input` elements and others that have a native `change` event I believe.

**Comment by Gorzas** [comment]
@pzuraq Thanks for the quick response! I've seen that this information is in the API docs. Can we include it also in the README? I think it's important to know that the decorator actions can override these hooks. What do you think?

**Comment by pzuraq** [comment]
I think adding a Caveats section to the README would be a good idea here, definitely. We can document all the major deviations from the standard Ember object model in one place.

**Comment by pzuraq** [comment]
There's a lot of work going on to get documentation into a better place in general, I'm working with the Ember Learn team on [ember-cli-addon-docs](https://github.com/ember-learn/ember-cli-addon-docs) with a goal of trying to build a simple unified system for creating documentation for addons. Once that work is done I'll be updating what we have here to match, and I'll be adding those caveats! This hasn't been forgotten!

**Comment by pzuraq** [comment]
Closing this since it's been consolidated into #203
