### ISSUE TITLE
Question: deprecation is telling me the fun times seem to be over? 

### ISSUE THREAD

**Issue by danielspaniel** [ember-decorators/ember-decorators#175]
I notice the new deprecation away from doing this 
```javascript
@computed('first', 'last')
name(first, last) {
  return  `${first} ${last}`;
}
```
suggests that we now do this:
```javascript 
@computed('first', 'last')
get name() {
   const first = this.get('first');
   const last = this.get('last');
  return `${first} ${last}`; // => 'John Smith'
}
```
 Really >?#
 That is such a buzz kill .. 
 The fun times of the decorators was that it passed you the values into the method. 
  Is there an extra great reason to use the get/set style you are proposing.

**Comment by pzuraq** [comment]
We plan on extracting the decorators that wrap `ember-macro-helpers` into a new library before this functionality is removed. This style is more inline with native Ember, which is why we’re making it the default.

**Comment by pzuraq** [comment]
For what it's worth, we're also planning on moving toward a more ergonomic approach in general:

```js
@computed('first', 'last')
get name() {
  const { first, last } = this;
  return `${first} ${last}`; // => 'John Smith'
}
```

@rwjblue suggested doing something more like this could be possible. Now that I'm thinking about it, we may actually be able to do this wrapping directly using the decorators, unsure if there's a plan to move towards it in Ember Core though so wanna see what they have planned first

**Comment by danielspaniel** [comment]
Are you saying we going to eventually do things the way ember-macro-helpers work ??

```javascript
name: computed('first', 'last', (first, last) => `${first} ${last} )
```

 your other idea is ok .. maybe a touch better,  but still boring

**Comment by pzuraq** [comment]
Kind of, currently we use ember-macro-helpers for this style of computed:

```js
@computed('first', 'last')
name(first, last) {
  return  `${first} ${last}`;
}
```

If you look at the code, you can see it just passes it off directly to ember-macro-helpers. The idea is to create a new library, ember-macro-helper-decorators (open to better name suggestions 😛) that does the same thing directly. This would allow users to choose between this style of computed and the ember-macro-helpers style by importing it from the corresponding library.

Like I said, the plan is to make sure that library exists before it's removed from this one, so don't worry there will definitely be an upgrade path!

**Comment by danielspaniel** [comment]
Ok .. I know your not going to just dump a pile of poop on everyone but I am 100% definitely not going to do this: 

```javascript 
@computed('first', 'last')
get name() {
   const first = this.get('first');
   const last = this.get('last');
  return `${first} ${last}`; // => 'John Smith'
}
``` 
that is for sure

**Comment by pzuraq** [comment]
Yeah, totally with you there, it's not a fun or ergonomic syntax at all. I'm liking the approach @rwjblue suggested because it brings how CPs and normal properties and getters work inline with each other, but I definitely thing the ember-macro-helpers style is valid too.

I made the repo for the library [here](https://github.com/ember-decorators/ember-macro-helper-decorators), PRs definitely welcome. I'm swamped for time at the moment, but when I get a chance I'll start working on it.

**Comment by danielspaniel** [comment]
That repo is empty .. but when you get going I can help out.

**Comment by rwjblue** [comment]
> your other idea is ok .. maybe a touch better, but still boring

Haha, sorry it isn't entertaining to you @danielspaniel 😝

**Comment by danielspaniel** [comment]
Glad you can laugh along , cause I think you know what I trying to say .. ¯\_(ツ)_/¯

**Comment by kellyselden** [comment]
I would think more about the name. ember-macro-helpers-decorators is a mouthful, and no one cares that the base library is in the name. ember-auto-computed-decorators or something that describes its purpose, not its base library, might be better.

**Comment by pzuraq** [comment]
Definitely agree, I’m open to bikeshedding on the name, just wanted to get the project started. I think ember-auto-computed-decorators is pretty good, can switch the repo name to that

**Comment by egemon** [comment]
@pzuraq could u please explain one more time, what is wrong with old syntax except that it requires some additional dependency AFAIU?

**Comment by pzuraq** [comment]
There's nothing wrong with the syntax itself or the ideas behind it, but it is divergent from the way standard Ember computeds work. Since this library is now focusing on providing decorators only for ES classes (decorators will not work with POJOs in the stage 2/3 proposal, I believe), we're also trying to make sure that every basic Ember concept has an equivalent in this library. Since macro-computeds are not vanilla Ember, we had a conflict, so we made the decision to add the new syntax which just wraps `Ember.computed` directly and deprecate the old syntax.

I will say that with longer term, the macro-computed and standard computed styles may end up conflicting in some ways. Now that we have decorators and native ES getters/setters, it may be possible to get rid of `get/set` altogether at some point in the future. With `get` this would actually be very simple, and we may be able to do it directly in this library, so that you would do:

```js
class Foo {
  @computed
  get bar() {
    return 'baz';
  }
}

let foo = new Foo();

console.log(foo.bar); // 'baz'
```

**Comment by egemon** [comment]
Thanks for the explanation.
