### ISSUE TITLE
runloop decorators

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#179]
Reference: [`@ember/runloop` package](https://emberjs.com/api/ember/2.16/modules/@ember%2Frunloop)

Members of that package (possibly relevant functions in bold):

- [ ] **[`bind`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=bind)**
- [ ] [`begin`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=begin)
- [ ] [`cancel`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=cancel)
- [ ] **[`debounce`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=debounce)**
- [ ] [`end`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=end)
- [ ] **[`join`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=join)**
- [ ] **[`later`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=later)**
- [ ] **[`next`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=next)**
- [ ] **[`once`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=once)**
- [ ] **[`schedule`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=schedule)**
- [ ] **[`scheduleOnce`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=scheduleOnce)**
- [ ] **[`throttle`](https://emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods?anchor=throttle)**

Signing up for a PR! :smile: 

Prior art: [`ember-run-decorators`](https://www.npmjs.com/package/ember-run-decorators)

**Comment by pzuraq** [comment]
For `bind`, we can write autobind functions like this in classes:

```js
class Foo {
  eventHandler = (e) => {
    // do something
  }
}
```

I think this is a better solution for that since it just relies on the semantics of class fields, so less overhead.

I think `@throttle` and `@debounce` could be pretty useful. I wonder if they could be made generic, they don't necessarily need to use the runloop tbh 🤔 definitely open to these though

**Comment by buschtoens** [comment]
IMHO that arrow function syntax is better as well, however `bind` also makes sure, that the function is called inside a run loop.

From the API docs: 

> Allows you to specify which context to call the specified function in **while adding the execution of that function to the Ember run loop**.

--- 

>  I wonder if they could be made generic, they don't necessarily need to use the runloop tbh 

I'm no Ember run loop expert. I just try to remember to always use something like `run`, when interfacing with external, non-Ember asynchrony to avoid strange bugs. I would apply that principle to stuff like `setTimeout`—if I was using it instead of `later`—as well. Therefore I think making `@throttle` and `@debounce` not use the run loop could potentially introduce problems.

But again, I have close to zero expertise on that topic. :sweat_smile: 

If you can enlighten me, please do. :smile:

**Comment by pzuraq** [comment]
Ah, good point, didn't realize that. My main concern there would be that the syntax would be confusing then, since it would likely be called directly and without the `run.bind` context it's unclear if it's a `run` bind or a normal autobind, just by looking at it. I suppose you could call it like `@run.bind` though.

You are correct, specifically you need to wrap any code that could call `run.schedule` in a runloop. Usually that'll be doing something like `set` or mutating state - you can read state just fine without having to schedule anything. For `@throttle` and immediate `@debounce` (where we call the function first and then trigger the debounce period) it would be pretty simple:

```js
throttled = throttleFunction(fn, timeout) {
  let waiting = false;

  return function(...args) {
    if (waiting) return;

    fn(...args);
    waiting = true;

    setTimeout(() => waiting = false, timeout);
  }
}
```

The key thing here is every time the throttled function is called, it is called from a context in which there is already a runloop (assuming we aren't doing anything else async). The asynchrony is just surrounding whether or not we call the function, so it's "safe". Same with debounce - _unless_ it's called after the wait period because then the function itself is being called async. So I guess in the end I agree, probably best to wrap the runloop functions here 😝 

I'm still not sure about the other functions, but I think those two would be fine, and possibly `bind`

**Comment by pzuraq** [comment]
We've decided to shelve these decorators for the time being. They may be useful, but there are lots of changes coming up to the decorators spec which we'll have to be ready for, and there are lots of changes coming up for the runloop which may make usage of `Ember.run` less necessary in general. I think we should wait it out and reconsider these in time.

**Comment by jnkroeker** [comment]
What is the latest thinking here?

**Comment by pzuraq** [comment]
We aren’t actively pursuing these decorators, and in general I believe the goal with the runloop is to make it so that it isn’t something users have to use regularly. For instance, unit tests no longer through if a runloop wasn’t scheduled, stuff like that.

**Comment by buschtoens** [comment]
> but it definitely doesn’t need to be Ember specific

One interesting, Ember-specific aspect though is object instance destruction.

There's [ember-lifeline-decorators](https://github.com/buschtoens/ember-lifeline-decorators) which wraps [ember-lifeline](https://github.com/ember-lifeline/ember-lifeline) in decorators. Problem is that `@throttle` and `@debounce` don't work (https://github.com/buschtoens/ember-lifeline-decorators/issues/3), because of https://github.com/ember-lifeline/ember-lifeline/pull/248. Unfortunately that PR has gone stale and development on ember-lifeline seems to have stalled a bit in general.

The [other decorators](https://github.com/buschtoens/ember-lifeline-decorators#available-decorators) work fine.

I was contemplating creating a new addon that essentially does the same as ember-lifeline-decorators, without ember-lifeline.

Another somewhat orthogonal idea is creating a "gating" decorator that only executes the method, if `!this.isDestroying && !this.isDestroyed`. Then you could compose more easily with generic JS decorators:

```js
class FooComponent extends Component {
  @debounce(500)
  @unlessDestroyed
  setSomething() {
    set(this, 'foo', 'bar');
  }
}
```

**Comment by pzuraq** [comment]
Ah, nice library 😄that looks like a great place to experiment with these patterns. I was also looking at [core-decorators](https://github.com/jayphelps/core-decorators) which had a `@debounce` and `@throttle`, but they also appear to be deprecated (and the library hasn't updated to the latest spec in some time).

Just to give some context, there are two major changes that should happen that will help to make `ember-lifeline` less necessary:

1. We're hoping to do some internal refactors to to metal in the next year that'll make memory leaks a thing of the past, at least based on cycles in `computed`s or `observer`s.
2. Element modifiers should be a more natural place to handle common use cases like event listeners, and we think we should be pushing lifeline users that direction.

But the other decorators may still be useful, especially as a generic decorator library. I wonder if there's some way we could make the notion of "destroyed" generic, so you could hook it into any component (or other) library for gating, I think that would be pretty useful.

**Comment by pzuraq** [comment]
It would probably be possible with hooks, you could replace the existing `willDestroy` method (or equivalent in other frameworks) with one that hooks into the decorators. Although hooks/extras are probably the most likely thing to change in the current spec 😕
