### ISSUE TITLE
@readOnly incompatibility with @computed

### ISSUE THREAD

**Issue by ming-codes** [ember-decorators/ember-decorators#192]
```
  @readOnly
  @computed('model')
  get guides() {
  }
```

Using getter raises an assertion error:

```
Error: Assertion Failed: Computed properties that define a setter using the new syntax cannot be read-only
```

However, using it without getter raises the deprecation message

```
  @readOnly
  @computed('model')
  guides() {
  }
```

```
DEPRECATION: using @computed with functions directly will be removed in future versions, using ES getter/setter functions instead [deprecation id: macro-computed-deprecated]
```

What is the right way to use `@readOnly`?

**Comment by buschtoens** [comment]
You can use @ember-decorators/auto-computed instead of `@computed` to avoid the deprecation. 

Regarding the first assertion: I think we should modify `@readOnly` to create a setter that just throws an error, if none exists, in order to be functionally equivalent to read only traditional Ember CPs.

**Comment by pzuraq** [comment]
@buschtoens we actually already do this, using `@computed` without a setter and attempting to set it will throw an error. This is more inline with native setters, which will also throw an error if they weren't defined and you attempt to set them.

I think this is a better behavior by default since it prevents strange things like `@computed` clobbering in general. It also basically makes the `@readOnly` decorator mostly useless - it's only useful now for modifying macros like `@alias`. We've decided to bring back the `@readOnly` macro in v2.0.0 because of this:

```js
import { readOnly } from '@ember-decorators/object'; // Modifier
import { readOnly } from '@ember-decorators/object/computed'; // Macro
```

We were initially worried about the overlap causing confusion, but because the modifier has such limited use cases now I'm not sure that'll be an issue. If it becomes one, we can probably figure out a solution.

**Comment by pzuraq** [comment]
Closing this issue for now, this should be better addressed by the upcoming docs site. The `@readOnly` decorator has been deprecated.
