### ISSUE TITLE
feature request: `@default()` property decorator

### ISSUE THREAD

**Issue by oliverlangan** [ember-decorators/ember-decorators#221]
Working in ES6 classes, I was initially bitten by the fact that class property initializers are run _after_ the properties are passed in to components. The issue is described well here:

https://github.com/typed-ember/ember-cli-typescript/issues/151#issuecomment-368029737

A solution that works well is to use the lodash `defaultTo` method, for example:
```
class MyComponent extends Component {
  foo: string = defaultTo(this.foo, 'foo default value');
}
```

But that would look better with a property decorator:
```
class MyComponent extends Component {
  @default('foo default value')
  foo: string;
}
```

**Comment by pzuraq** [comment]
_o ve ras'n

**Comment by pzuraq** [comment]
So we can't actually use the work `default` because it's a keyword in Javascript, but we actually have already built this out over in https://github.com/ember-decorators/argument 😄 

There are some extra validations which are layered on top of the decorator as well. For components, it'll tell you if you tried to use an argument which doesn't exist, and there are other validation decorators too. Those may be split out into their own package at some point, but for now they're all completely stripped from production builds so they won't add any extra weight to your app!

**Comment by oliverlangan** [comment]
Ah, of course yes `default` is a reserved word. `@argument` looks great, I will close this and go with that, thanks! I'll also add a link to it to the conversation linked above, since others may wish to use it as well.
