### ISSUE TITLE
Add eslint-ember-decorators plugin

### ISSUE THREAD

**Issue by artemgurzhii** [ember-decorators/ember-decorators#222]
When working on the multiple ember projects with different setups, or when you just don't know that `ember-decorators` has this option I'm having

```js
@service session: null,
```
in one file, and
```js
session: service(),
```
in other.

I was thinking about eslint plugin(such as [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember) or [eslint-plugin-ember-best-practices](https://github.com/ember-best-practices/eslint-plugin-ember-best-practices)) which will able to throw errors when you are using `ember-decorators` but not using some of their available decorators.

**Comment by pzuraq** [comment]
I'm not sure this will be as relevant now that decorators are no longer supported when used with POJO syntax. If you're using native classes, you must use decorators. Otherwise, you can _not_ use decorators.

We'll be working on a codemod to make the transition to using decorators with native classes smoother, and ideally it will work with converting any usage of decorators on POJOs as well. I'm going to close this for now, but if you have any specific suggestions for eslint rules we can add we're definitely open to suggestions!
