### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sly7-7** [ember-decorators/ember-decorators#243]
During `ember install ember-decorators`, when installing babel-eslint package, this error is thrown: 

```
"ENOENT: no such file or directory, copyfile '/Users/sma01/Library/Caches/Yarn/v1/npm-@babel/generator-7.0.0-beta.44-c7e67b9b5284afcf69b309b50d7d37f3e5033d42/README.md' ->'/Users/sma01/work/git/gitlab/erdil/esatis/frontend/node_modules/@babel/generator/README.md'"
```

**Comment by pzuraq** [comment]
It looks like this is a failure within the package manager, we don’t do any manual copying within node_modules.

**Comment by rtablada** [comment]
I've run into this as well. I'm not sure quite where the issue is and haven't tried reliably recreating this.

But I suspect that the pattern to recreate looks something like:

```
ember new foo --yarn
ember install ember-cli-typescript
ember install ember-decorators
```

I'm not sure if the error is in decorators, CLI, or yarn.

I'll try to investigate later this weekend though because I've run into it on two projects today... 😢 

My work around was to remove the `yarn.lock` file, remove `node_modules`, install with `npm`, run `ember g ember-decorators`, then either keep using `npm` for the project or remove all node_modules and rebuild with yarn.

**Comment by pzuraq** [comment]
I'm wondering if it may be trying to install both addons at once and is running `yarn` multiple times, I know yarn has issues with parallelization in general and running it twice in the same project could be an issue

**Comment by pzuraq** [comment]
I merged a change to run the installs sequentially instead of in parallel. Let me know if that appears to work!
