### ISSUE TITLE
@on('init') called before fields are set

### ISSUE THREAD

**Issue by boris-petrov** [ember-decorators/ember-decorators#293]
This caught me by surprise. Having:

```javascript
import { A } from '@ember/array';
import Service from '@ember/service';
import { observes, on } from '@ember-decorators/object';

class A extends Service {
  x = A();

  @on('init')
  @observes('asd')
  foo() {
    console.log(this.x); // this will print undefined
  }
}
```

I understand what happens (that this is translated to setting `x` in the constructor but only after `super` is called which actually calls the `@on('init')` hook and that's why it is undefined) but... this is pretty horrible. :) Is there something you can do about it? Or Ember.js? And how do you circumvent it?

**Comment by rwjblue** [comment]
FWIW, you are describing the _exact_ reason that https://github.com/emberjs/rfcs/pull/337 was submitted. That RFC has already been implemented, and is scheduled for release in Ember 3.6 (in a few weeks).

**Comment by rwjblue** [comment]
I'm going to close this (because you are right, and we did do something about it 😉 )...

**Comment by boris-petrov** [comment]
@rwjblue - thank you very much, that's really good news! Just a quick question about this: `Injections and the init hook` - it says `One side effect of this change is that injections will not be available on the class instance during the constructor phase` - we actually use that a lot in our code and this will be a big breaking change (not that it should stop you from going forward with releasing this of course). I was wondering whether it's not possible to do the injections first (before calling the constructor) as is right now and only then do the rest of the stuff? I'm obviously not familiar with how these things work under the hood but it would be nice to be like so - otherwise as I understand we'll have to override `init` in some places and use `constructor` in others and that's kind of a mess... :)

**Comment by pzuraq** [comment]
Hey @boris-petrov, that's a good question! Unfortunately due to the way injections currently work, it is not possible. However, it _may_ be possible in the future. This is ultimately something that needs to be decided about how we want to handle classes in future versions of Ember, when we are able to fully deprecate `EmberObject`. You can check out some of the ideas for that in the [Native Class Roadmap RFC](https://github.com/pzuraq/emberjs-rfcs/blob/b47e7f9ec4f02c7d27d50de64691130e7d22747d/text/0000-native-class-roadmap.md).

However, in the short term the solution is to use _always_ use the `init` hook instead of `constructor`. This is going to be the officially recommended path, because `init` essentially identical to `constructor` with the exception of this change. You can think of it as "initialized by the container" if that makes more sense.

As an early adopter I realize this is probably inconvenient for you, believe me we tried to find a different way for quite some time. However, this _should_ be very easy to codemod! It's just renaming a function and changing a `super` call. I'll see if I can write one real quick once I get into the office today!

**Comment by rwjblue** [comment]
> I was wondering whether it's not possible to do the injections first (before calling the constructor)

Just to be clear, it's not possible to do _anything_ to an instance before the `constructor` runs because that's what creates an instance... 😄

**Comment by pzuraq** [comment]
True! I was more meaning, there _are_ ways we could assign injections in the base class before _subclass_ constructors run. Personally, I think the `init` hook actually makes some sense if you understand what the constructor is doing, but at the same time I think it may not be intuitive to users (this issue being evidence of that).

There are a few different options, but they all require us picking an architecture to succeed `EmberObject`, which is a much larger conversation to be had.

**Comment by boris-petrov** [comment]
Thank you both for the thorough explanations! I of course meant doing the injections before the *subclass* constructor is called (which I guess essentially happens now). :) Anyways, thanks! I'll be sure to rewrite our code to use `init` instead of `constructor`. And you make sure to document this well enough for everyone to understand. :) Thank you!
