### ISSUE TITLE
Cannot read property 'initializer' of undefined

### ISSUE THREAD

**Issue by boris-petrov** [ember-decorators/ember-decorators#322]
Updating to version 3.1.2 causes that exception in the `convertStage1ToStage2` function.

I do have the following warnings in the console but I had them before also and it was working fine. :)

```
WARNING: @ember-decorators/babel-transforms: You are using an unsupported ember-cli-babel version, decorator/class-property transforms will not be included automatically
WARNING: Your app is using an older version of ember-cli-typescript that uses stage 1 decorators. Please update to ember-cli-typescript@v2 to remove your dependency on legacy decorators.
```

**Comment by buschtoens** [comment]
The cause likely is:

> WARNING: @ember-decorators/babel-transforms: You are using an unsupported ember-cli-babel version, decorator/class-property transforms will not be included automatically

What version of ember-cli-babel are you using?

```
yarn list --pattern ember-cli-babel
```

**Comment by boris-petrov** [comment]
@buschtoens - I'm still on 6.17.2 as I'm waiting on [your PR in ember-auto-import](https://github.com/ef4/ember-auto-import/pull/157). But, as I said, this is working fine on `ember-decorators` 3.1.1 even with the warning. Perhaps it shouldn't be?

**Comment by buschtoens** [comment]
Oh, so you're using this in conjunction with `ember-cli-typescript@1`?

**Comment by boris-petrov** [comment]
Yes, as `ember-cli-typescript` 2 requires `ember-cli-babel` 7 which is broken in `ember-auto-import`. :) It shouldn't be working in 3.1.1 I suspect? :)

**Comment by buschtoens** [comment]
I was wondering why it used to work at all with `3.1.1`, since the `decorator/class-property` warning means that `@ember-decorators/babel-transforms` did not install any transforms, thus decorators and class properties would not get transformed.

_However_, you also have `ember-cli-typescript@1`, which uses `tsc` to transform all `*.ts` files. `tsc` has its own decorator and class property transforms, which is why it works at all. FWIW you could verify this by disabling `allowJs` in your `tsconfig.json` (if not already), which should force `ember-cli-typescript@1` to ignore `*.js` files. If you then try to use decorators in any `*.js` file, Babel should crash.

Anyhow, it seems like you have discovered a bug in how we handle decorators as transpiled by `ember-cli-typescript@1`. The problem specifically is:

https://github.com/ember-decorators/ember-decorators/blob/0d5c47c3dc0e3a99eacb4d98f071fca9935c55e0/packages/utils/addon/decorator.js#L56-L64

`desc` _is_ an array with three elements, but the last elements (`descriptor`) is `undefined`.

Can you please share that part of your code that causes this error?

**Comment by buschtoens** [comment]
Caused by https://github.com/ember-decorators/ember-decorators/pull/318.

**Comment by boris-petrov** [comment]
Well, I can't really say which part of the code... the stacktrace is in the Application Route where some code has been injected:

```javascript
var __decorate = undefined && undefined.__decorate || function (decorators, target, key, desc) {
        var c = arguments.length,
            r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc,
            d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };
```

And at the bottom this `__decorate` function is called with one of the things that I import... there's literally no code of mine. :) Can I help with something more?

Thank you for the explanations, they make sense!

**Comment by buschtoens** [comment]
I meant the actual _source code_, not the transpiled code 😅 

Can you try creating a new class with a minimal reproduction?

**Comment by boris-petrov** [comment]
Well, I meant that this code was injected by someone else (I guess `tsc`) - this is not my code. :) Anyway, here is a reproduction:

https://github.com/boris-petrov/decorators-bug

I did something like:

```
ember new decorators-bug
ember install ember-decorators
ember install ember-cli-typescript
*** add "experimentalDecorators": true to tsconfig.json
```

Run `ember server` and see open the page.

**Comment by buschtoens** [comment]
[This](https://github.com/boris-petrov/decorators-bug/blob/master/app/routes/application.ts) is all I needed and meant 😄 

``ts
import Route from '@ember/routing/route';
import { service } from '@ember-decorators/service';
import Foo from 'ember-decorators/services/foo';

export default class extends Route {
  @service
  private readonly foo!: Foo;
}
```

Thanks for the full reproduction repo though! :)
