### ISSUE TITLE
`init` vs `constructor`

### ISSUE THREAD

**Issue by Caltor** [ember-decorators/ember-decorators#329]
Should we be using `init` or `constructor` in components with ES classes?

This recent issue https://github.com/ember-decorators/ember-decorators/issues/294 seems to imply we should be using `init`, so I have created a simple component as follows:
```
import Component from '@ember/component';
export default class TestComponentComponent extends Component {
    init() {
        this._super(...arguments);
    }
}
```

However when I use this component I get the following erroneous error from jquery:

> Assertion Failed: You must call `this._super(...arguments);` when overriding `init` from a framework object.

If I change it to this instead as per this OLDER issue https://github.com/ember-decorators/ember-decorators/issues/294 then it works fine!?!

```
import Component from '@ember/component';
export default class TestComponentComponent extends Component {
    constructor() {
        super(...arguments);
    }
}
```

So which should it be???

**Comment by pzuraq** [comment]
You _should_ be using `init` instead of `constructor`. You also should _not_ be using `_super`, since that is the old object model's way of calling super. Instead, you should use the `super` keyword, as you would in standard native classes:

```js
import Component from '@ember/component';

export default class TestComponentComponent extends Component {
    init() {
        super.init(...arguments);
    }
}
```

Also note that native class syntax is _not_ supported in Ember until version 3.6, with polyfills working for v3.4 and v3.5. If you use native class syntax before those versions, there will be different behavior surrounding the constructor. See [this RFC](https://github.com/emberjs/rfcs/blob/master/text/0337-native-class-constructor-update.md) for more details on that.

**Comment by pzuraq** [comment]
You have to remove ember-decorators, which you should anyways if possible, since decorators can only be used with native classes.

**Comment by pzuraq** [comment]
If you cannot for some reason, you could also remove `ember-decorators` directly, and add the individual packages you want to use (e.g. `@ember-decorators/object`)

**Comment by Caltor** [comment]
@pzuraq Great advice, thanks!

**Comment by Caltor** [comment]
Do you think it would be a good idea to have an example `init()` in the docs or is that out of scope for this project?

**Comment by pzuraq** [comment]
Yes, I think this would be a good addition for the `constructor vs init` section: https://ember-decorators.github.io/ember-decorators/docs/native-class-basics#constructor-vs-init

We should show folks how to use init, specifically that they must use `super`.

**Comment by Caltor** [comment]
@pzuraq Added PR https://github.com/ember-decorators/ember-decorators/pull/331. BTW The "Edit this page" link on the documentation doesn't work for me (or presumably anyone) and I couldn't find where it comes from to fix it.
