### ISSUE TITLE
@componentManager

### ISSUE THREAD

**Issue by buschtoens** [ember-decorators/ember-decorators#335]
I propose we already add the `@componentManager` decorator to the `@ember-decorators/component` package, while [RFC #408 Decorators](https://github.com/emberjs/rfcs/pull/408) is still shaking out.

Happy to submit the PR.

### Spec

> Ember will provide a new API to assign the component manager for a component
> class:
> 
> ```js
> // my-app/app/components/foo-bar.js
> 
> import EmberObject from '@ember/object';
> import { setComponentManager } from '@ember/component';
> 
> export default setComponentManager('awesome', EmberObject.extend({
>   // ...
> }));
> ```
> 
> This tells Ember to use the `awesome` manager (`component-manager:awesome`) for
> the `foo-bar` component. `setComponentManager` function returns the class.
> 
> In the future, this function can also be invoked as a decorator:
> 
> ```js
> // my-app/app/components/foo-bar.js
> 
> import EmberObject from '@ember/object';
> import { componentManager } from '@ember/component';
> 
> export default @componentManager('awesome') EmberObject.extend({
>   // ...
> });
> ```

### References

- [RFC #213 Custom Components API](
 https://github.com/emberjs/rfcs/blob/master/text/0213-custom-components.md#determining-which-component-manager-to-use)
- https://github.com/emberjs/ember.js/issues/16301

**Comment by rwjblue** [comment]
AFAICT the decorator doesn't actually provide any value (the resulting code is actually more characters, and isn't simpler to comprehend)? What am I missing?

**Comment by rwjblue** [comment]
Also, that isn't the API for `setComponentManager` as of 3.8.

https://emberjs.github.io/rfcs/0392-deprecate-component-manager-string-lookup.html

**Comment by buschtoens** [comment]
> AFAICT the decorator doesn't actually provide any value (the resulting code is actually more characters, and isn't simpler to comprehend)? What am I missing?

To me, especially when using native class syntax, the `@componentManager` looks cleaner than wrapping that class in `setComponentManager`.

Taking the changes in RFC 392 into account (thanks!) it would be:

```ts
import { createManager } from './basic-manager';
import { setComponentManager } from '@ember/modifier';

export default setComponentManager(createManager, class MyComponent {
  // ...
});
```

vs

```ts
import { createManager } from './basic-manager';
import { componentManager } from '@ember-decorators/component'; // or modifier?

@componentManager(createManager)
export default class MyComponent {
  // ...
}
```

But that's probably subjective. Is the `@componentManager` completely off the table or would you just want to wait for it to land upstream instead?

**Comment by pzuraq** [comment]
IMO `setComponentManager` is _effectively_ a class decorator and this is the right move, in the long run. Right now though, the decorators RFC is proposing the minimum viable amount of decorators required to be able to use native class syntax because they are still unstable. 

Post RFC, `ember-decorators` will likely become two distinct sets of decorators - the polyfill for the RFC, and decorators needed for classic feature support that were not included in the RFC. `@componentManager` doesn't really fit in either category. Combining this with the fact that it is not really meant to be a commonly used API, I don't think making a decorator just now is really necessary.

I would wait until decorators reach stage 3 (or even stage 4) and then RFC it to Ember directly. It's an API that will likely be used in a handful of addons in the meantime, so there won't be a huge impact of waiting for stability.

**Comment by buschtoens** [comment]
> IMO `setComponentManager` is _effectively_ a class decorator and this is the right move, in the long run.

Which is the reason, why I wanted to make it available as a "proper" decorator, so that consumers may use nicer syntax.

But considering the arguments you both have brought forth, I can see that it is probably not worth the hassle right now. Thanks! 😊
