### ISSUE TITLE
Service decorator uses raw property name by default, whereas Ember default is to dasherize property name

### ISSUE THREAD

**Issue by lolmaus** [ember-decorators/ember-decorators#337]
When I do this:

```js
import { inject as service } from '@ember/service';

Component.extend({
  shoopDaWhoop: service()
})
```

The service gets registered as `shoop-da-whoop`.

But when I do this:

```js
import { service } from '@ember-decorators/service';

class Foo extends Component {
  @service
  shoopDaWhoop;
}
```

The service gets registered as `shoopDaWhoop`.

Note that in both cases I used the same property name, yet the result was different.

We should follow the Ember convention to use dasherizing for internal representation of service names.

**Comment by lolmaus** [comment]
Relevant line: https://github.com/ember-decorators/ember-decorators/blob/master/packages/service/addon/index.js#L21

**Comment by buschtoens** [comment]
I am pretty sure that Ember does not internally dasherize it before passing it to `lookup`. Have you actually experienced any bugs?

`inject` from `@ember/services` returns an [`InjectedProperty`](https://github.com/emberjs/ember.js/blob/6aea56d221f0f4fc2a702a7729a36d581ad2c627/packages/%40ember/-internals/metal/lib/injected_property.ts#L57-L75), whose getter looks like this:

```js
function injectedPropertyGet(this: any, keyName: string): any {
  let desc = descriptorFor(this, keyName);
  let owner = getOwner(this) || this.container; // fallback to `container` for backwards compat

  assert(
    `InjectedProperties should be defined with the inject computed property macros.`,
    desc && desc.type
  );
  assert(
    `Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.`,
    !!owner
  );

  let specifier = `${desc.type}:${desc.name || keyName}`;
  return owner.lookup(specifier, {
    source: desc.source,
    namespace: desc.namespace,
  });
}
```

In the case where no explicit service name has been passed to `inject` / `service`, `desc.name` will be `undefined`. It thus defaults to `keyName` which is the actual name of the property. This means that Ember internally tries to resolve `service:shoopDaWhoop`, which works, because the lookup / resolver dasherizes names for you.

**Comment by buschtoens** [comment]
The normalization is performed here: https://github.com/ember-cli/ember-resolver/blob/5ed5bf8d243f473c6ff6b4281e35191fb73a3a8c/addon/resolvers/classic/index.js#L167-L185

**Comment by buschtoens** [comment]
> whereas EmberClear and our app are running Ember 3.6.0 Canary with MU.

This is likely the cause 👍
I suggest you jump down the rabbit hole and step through what happens inside of `owner.lookup`. In the MU case there is likely no normalization (with dasherization) happening.

**Comment by buschtoens** [comment]
Just ran into this as well and reported it upstream with a workable analysis. 😊 

https://github.com/ember-cli/ember-resolver/issues/299
