### ISSUE TITLE
Assertion Failed: The @on decorator must be applied to functions

### ISSUE THREAD

**Issue by chenxu-javascript** [ember-decorators/ember-decorators#366]
code 
```
import { on } from '@ember-decorators/object';
export default Component.extend({
  @on('didInsertElement')
  donInit() {
    console.log(123);
  }
});
```

and the run result 

![image](https://user-images.githubusercontent.com/16332458/50630304-4b494d80-0f7b-11e9-91b3-d19be3a0aa98.png)

```
  "ember-decorators": "^4.0.0",
  "ember-source": "~3.6.0",
  "@babel/plugin-proposal-decorators": "^7.2.3",
  "@ember-decorators/babel-transforms": "^3.1.5",
  "@ember/jquery": "^0.5.2",
  "@ember/optional-features": "^0.6.3",
  "babel-eslint": "^8.2.6",
```

Thanks in advance to the author, how can I operate correctly?

thanks again

**Comment by buschtoens** [comment]
Using decorators on plain object literals is deprecated. Please us a "real native" class instead:

```ts
import Component from '@ember/component';
import { on } from '@ember-decorators/object';

export default class FooComponent extends Component {
  @on('didInsertElement')
  donInit() {
    console.log(123);
  }
}
```

You can find more info on native classes in the docs: [Why Go Native?](https://ember-decorators.github.io/ember-decorators/docs/why-go-native)

**Comment by pzuraq** [comment]
We should add error messages that assert against this case now, we honestly should have done it when we stopped supporting it 😕

**Comment by chenxu-javascript** [comment]
before code
```
import Component from '@ember/component';
import { computed } from '@ember-decorators/object';

export default Component.extend({
  pagebar: null,
  tagName: '',
  @computed('pagebar')
  hasMore(pagebar={}) {
    let { page=1, limit=1, total=0 } = pagebar;
    return Math.ceil(total/limit) > page;
  }
});
```

**Comment by pzuraq** [comment]
Unfortunately the codemod currently only supports transforming from classic syntax _without_ decorators to native class syntax, which is why you're running into the issues you have 😕 there is an open issue to create a codemod that would help folks who adopted decorators when they were still compatible with POJO syntax, but I'm unsure when we'll be able to work on that

**Comment by pzuraq** [comment]
@chenxu-javascript The codemod part of this issue is covered by #206, and we won't be supporting the stage 1 transforms for too much longer. When we do drop those, users won't be able to use the decorators in POJOs at all, so we'll get earlier warnings I think. If not, we should definitely add errors when used on POJOs.
