### ISSUE TITLE
`@queryParam` decorator

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#381]
Based on a convo in Discord, it seems like a `@queryParam` decorator that decorates individual properties would be a good idea for ergonomics. Strawman design:

```js
queryParams: ['p:page'],
page: 1,

//vs

@queryParam('p')
page = 1;
```

We need to make sure we cover all forms of queryParams current use in both routes and controllers. Once we have the design locked down, we can move forward with implementation.

**Comment by robclancy** [comment]
So here is our query params in one of our filterable lists. In the controller.

```js
queryParams = [
    'page',
    'title',
    'status',
    'assignees',
    'clients',
    'projects',
    { clientType: 'client-type' },
    { dueBefore: 'due-before' },
    { dueAfter: 'due-after' },
    { contentCreator: 'content-creator' },
  ];
  page = 1;
  title = '';
  status = [];
  assignees = [];
  clients = [];
  clientType = '';
  dueBefore = '';
  dueAfter = '';
  contentCreator = '';
  projects= [];
```

We can make query params far better with decorators simply because we can combine all this into 1 property.

```js
@queryParam('page')
page = 1;
```

First question, do we have (can we? I have no idea how this works) the query param default to the variable name? So in this case we don't include the `'page'`.

```js
@queryParam page = 1;
```

And if that first argument does exist we can use it as the query param in the URL.

---

Next thing, do we want to keep doing this hacky way that ember does things where it uses the default value type to workout the type for that query param? Or would we want to pass the type into the decorator? ie..

```js
@queryParam('int') page = 1;
```

With the second parameter being the URL query param if specified.

---

So here is my first set of filters changed to be what I think is the most straight forward way of doing this...

```js
  @queryParam 
  page = 1;
  
  @queryParam 
  title = '';
  
  @queryParam 
  status = '';
  
  @queryParam 
  assignees = [];
  
  @queryParam 
  clients = [];
  
  @queryParam 
  projects = [];
  
  @queryParam('client-type') 
  clientType = '';

  @queryParam('due-before')
  dueBefore = '';

  @queryParam('due-after')
  dueAfter = '';

  @queryParam('content-creator')
  contentCreator = '';
```

With keeping the default way ember does things by inferring the query param type by getting the type of the default value I think this decorator becomes fairly simple. Just have to build the `queryParams` array in the constructor (once again I have no idea how these things work I'm just guessing).

---

As for routes, I think we don't change how it works. Personally I just have `refreshModel: true` over and over.

```js
queryParams: {
    page: {
      refreshModel: true,
    },
    title: {
      refreshModel: true,
    },
    status: {
      refreshModel: true,
    },
    assignees: {
      refreshModel: true,
    },
    unassigned: {
      refreshModel: true,
    },
    clients: {
      refreshModel: true,
    },
    clientType: {
      refreshModel: true,
    },
    taskType: {
      refreshModel: true,
    },
    dueBefore: {
      refreshModel: true,
    },
    dueAfter: {
      refreshModel: true,
    },
    contentCreator: {
      refreshModel: true,
    },
    projects: {
      refreshModel: true,
    },
  },
```

My plan for our project is simply to change the default for every query param to `refreshModel: true`. And also to have a far nicer API where we just do something like `queryParamsDontRefresh: []`.

We could potentially have a decorator here too. What I would really like is to move the controller decorators to the router, then we use the defined params on the route to build the controllers query params so they are all in one spot and also gives us less reason to need to create a controller in the first place.

**Comment by buschtoens** [comment]
Closing in favor of [`ember-query-params-service`](https://github.com/NullVoxPopuli/ember-query-params-service) by @NullVoxPopuli.

**Comment by NullVoxPopuli** [comment]
I plan to have a clear direction on that by Friday. Because the new decorators proposal isn't implemented yet, I need to write an RFC for ember's routing / acceptance-listing of query params.
