### ISSUE TITLE
Eslint error for @computed used with single dependent key

### ISSUE THREAD

**Issue by olegstepura** [ember-decorators/ember-decorators#397]
When I need to depend on only one property like this:
```js
  @alias('service.someProperty')
  selectedItems;

  @computed('selectedItems')
  get total() {
    let total = 0;
    this.selectedItems.forEach(item => {
      total += item.price;
    });
    return total;
  }
```
I get a eslint error:
```
.../index/controller.js
  16:4  error  Do not use Computed Properties without dependent keys. If you want the property to be set only once, initialize it in init(). Please see following guide for more information: https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/guides/rules/require-dependent-keys.md  ember-best-practices/require-dependent-keys
```

which is somewhat strange. 

I think that is because of support for description last parameter in `@computed` which makes single property just a description? I really find having descriptions there to be harmful since it will clash with string keys and makes it hard to read and understand:
```
  @computed('selectedItems', 'price')
```
^- not obvious that second parameter is actually a description, not a dependency...

Using latest version: `"ember-decorators": "5.1.2"`

**Comment by buschtoens** [comment]
This is a bug upstream in [`eslint-plugin-ember-best-practices`](https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/guides/rules/require-dependent-keys.md). Can you please open a ticket there and link it here?

**Comment by olegstepura** [comment]
Opened an issue there, thanks!

Did I understand it correct that `ComputedPropertyDesc` here is the actual computing logic that we write as `get propertyName` getter below `@computed`?
https://github.com/ember-decorators/ember-decorators/blob/1afca82f5932f101e59c573faf2ebc4d1dbc9c17/packages/object/published-types/index.d.ts#L119-L125

**Comment by buschtoens** [comment]
You're looking at the [TypeScript declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for `@ember-decorators/object`. You can identify a declaration file by its `.d.ts` extension. This file is used by IntelliSense to provide suggestions and `tsc` to perform type checking.

A declaration file only contains type information and no logic. This means that is has no effect at runtime.

TypeScript is implementing an outdated version of the decorators proposal, which is why we have to provide an extra declaration file with some special type massaging 💆 and can't just generate one from our source code.

The type for `ComputedPropertyDesc` is defined here:

https://github.com/ember-decorators/ember-decorators/blob/1afca82f5932f101e59c573faf2ebc4d1dbc9c17/packages/object/published-types/index.d.ts#L17-L21

It's composed of these types:

https://github.com/ember-decorators/ember-decorators/blob/1afca82f5932f101e59c573faf2ebc4d1dbc9c17/packages/object/published-types/index.d.ts#L3-L15

The ESLint issue you are having has nothing to do with these types, since ESLint is not type-aware. ☺️ 

The actual computing logic can be found in [`packages/object/addon`](https://github.com/ember-decorators/ember-decorators/tree/master/packages/object/addon). More specifically, this is the implementation of the `@computed` decorator:

https://github.com/ember-decorators/ember-decorators/blob/23c55cc279f1e3715a742836a55c74883042feaa/packages/object/addon/index.js#L161-L241

**Comment by olegstepura** [comment]
Hi, thanks for so detailed explanation. 

Sorry, I did not highlight my level anyhow, I know why those typescript definitions are there... But thanks anyways for the very detailed explanation which can help some googlers to understand those things.

I was just wondering if the last argument is an actual function to compute the property value same as it is in "regular" [ember computed helper](https://www.emberjs.com/api/ember/release/functions/@ember%2Fobject/computed). Now I've read the code you quoted and it seem like decorator only wraps the original computed helper, which answers my question.

Thanks!
