### ISSUE TITLE
get/set example doesn't pass key to set

### ISSUE THREAD

**Issue by devinus** [ember-decorators/ember-decorators#58]
The get/set example in the README doesn't seem to pass the `key` as the first argument to `set` like the standard Ember new CPs do. Is that intentional or a misprint?

<img width="483" alt="screen shot 2015-12-11 at 2 36 48 am" src="https://cloud.githubusercontent.com/assets/4836/11739315/28794ef6-9fb0-11e5-8207-b8dcf6152974.png">

**Comment by mattmarcum** [comment]
👍 I was wondering about this too

**Comment by buschtoens** [comment]
This is by design. It's more ergonomic for most cases.

If you want to create a reusable computed property that needs to know its name you have to pass it manually, as far as I can see.

You can also use the following pattern to make your CPs "configurable" (independent of their name).

There are two options:

#### Raw Parameters

Since **ember-decorators** wraps [**ember-macro-helpers**](https://github.com/kellyselden/ember-macro-helpers), you can use the [`raw` macro](https://github.com/kellyselden/ember-macro-helpers#raw).

I greatly prefer this variant, since it allows you to reuse the same function / object as the CP.

```js
import EmberObject from '@ember/object';
import { computed } from 'ember-decorators/object';
import raw from 'ember-macro-helpers/raw';

const computedProperty = {
  get(key, first, last) {
    return `${key}: ${first} ${last}`;
  },
  set(value, key, first, last) {
    // ...
  }
};

export default class extends EmberObject {
  @computed(raw('name'), 'first', 'last')
  name = computedProperty:

  @computed(raw('otherName'), 'first', 'last')
  otherName = computedProperty:
}
```

#### Computed Property Factory

```js
import EmberObject from '@ember/object';
import { computed } from 'ember-decorators/object';

function makeComputedProperty(key) {
  return {
    get(first, last) {
      return `${key}: ${first} ${last}`;
    },
    set(value, first, last) {
      // ...
    }
  };
}

export default class extends EmberObject {
  @computed('first', 'last')
  name = makeComputedProperty('name');

  @computed('first', 'last')
  otherName = makeComputedProperty('otherName');
}
```

**Comment by kellyselden** [comment]
This lib could re-export `raw` so the consumer wouldn't have to worry about it.

**Comment by pzuraq** [comment]
This should likely be moved to https://github.com/ember-decorators/auto-computed, this library no longer wraps `ember-macro-helpers`
